services:

  jobmanager:
    image: starrocks/flink
    build:
      dockerfile: ./flink.Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./mysql-to-starrocks.yaml:/opt/flink/flink-cdc-3.1.0/mysql-to-starrocks.yaml
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        

  taskmanager:
    image: starrocks/flink
    build:
      dockerfile: ./flink.Dockerfile
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2        

  sql-client:
    image: starrocks/flink
    build:
      dockerfile: ./flink.Dockerfile
    command: bin/sql-client.sh
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager

  StarRocks:
    image: starrocks/allin1-ubuntu:3.2.6
    ports:
      - "8080:8080"
      - "9030:9030"
  MySQL:
    image: debezium/example-mysql:2.1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
