services:
  jobmanager:
    image: starrocks/flink
    build:
      dockerfile: ./flink.Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./mysql-to-starrocks.yaml:/opt/flink/flink-cdc-3.1.0/mysql-to-starrocks.yaml
    command: jobmanager
    environment:
      - TZ=America/New_York
      - "FLINK_PROPERTIES=jobmanager.rpc.address: jobmanager"

  taskmanager:
    image: starrocks/flink
    build:
      dockerfile: ./flink.Dockerfile
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - TZ=America/New_York
      - "FLINK_PROPERTIES=jobmanager.rpc.address: jobmanager\n taskmanager.numberOfTaskSlots: 2"

  sql-client:
    image: starrocks/flink
    build:
      dockerfile: ./flink.Dockerfile
    command: bin/sql-client.sh
    depends_on:
      - jobmanager
    environment:
      - TZ=America/New_York
      - "FLINK_PROPERTIES=jobmanager.rpc.address: jobmanager\n rest.address: jobmanager"

  StarRocks:
    image: starrocks/allin1-ubuntu:3.2.6
    ports:
      - "8080:8080"
      - "9030:9030"
    environment:
      - TZ=America/New_York

  MySQL:
    image: debezium/example-mysql:2.1
    ports:
      - "3306:3306"
    environment:
      - TZ=America/New_York
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  postgres:
    image: debezium/example-postgres:2.1
    ports:
      - "5432:5432"
    environment:
      - TZ=America/New_York
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

